# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Johan Lorentzon
email: johanlorentzon@zoho.com
description: > # this means to ignore newlines until "baseurl:"
  Web Developer
about: >
  [Start Bootstrap](http://startbootstrap.com) is an open source library
  of Bootstrap themes and templates.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://lorentzon.co" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
github_username: sahuk
#facebook_username: StartBootstrap
#instagram_username: beyonce
stackoverflow_url: https://stackoverflow.com/users/6204204/sahuk
#googleplus_username: BobMarley
#skype_username: echo123
#linkedin_url: https://

# Address information
#address_street: 3034 Melrose Place
address_city: Linköping
address_state: Sweden
#address_zip: 90201
#
# Build settings
markdown: kramdown
